chore(lapis): revert upgrade of `springdoc-openapi-starter-webmvc-ui`
The OpenAPI docs fail to parse when generating the client:
```
Run npm run generateLapisClient

> lapis-e2e@1.0.0 generateLapisClient
> npm run runOpenApiGenerator && npm run copyGeneratedFiles && npm run cleanUpGeneratedFiles

> lapis-e2e@1.0.0 runOpenApiGenerator
> openapi-generator-cli generate -i ../lapis/lapis-openapi-single-segmented.json -g typescript-fetch -o generated-sources

Download 6.4.0 ...
Downloaded 6.4.0
[main] ERROR i.s.v.p.reference.ReferenceVisitor - Error resolving schema #/components/schemas/ProblemDetail
java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Boolean` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
[...]
```