chore(lapis): bump the minorandpatch group across 1 directory with 10 updates (#1102)
* chore(lapis): bump the minorandpatch group across 1 directory with 10 updates

Bumps the minorandpatch group with 10 updates in the /lapis directory:

| Package | From | To |
| --- | --- | --- |
| [org.springdoc:springdoc-openapi-starter-webmvc-ui](https://github.com/springdoc/springdoc-openapi) | `2.7.0` | `2.8.5` |
| [org.apache.commons:commons-csv](https://github.com/apache/commons-csv) | `1.12.0` | `1.13.0` |
| [com.github.luben:zstd-jni](https://github.com/luben/zstd-jni) | `1.5.6-8` | `1.5.7-1` |
| [com.github.ben-manes.caffeine:caffeine](https://github.com/ben-manes/caffeine) | `3.1.8` | `3.2.0` |
| [org.jetbrains.kotlinx:kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime) | `0.6.1` | `0.6.2` |
| [org.springframework.boot](https://github.com/spring-projects/spring-boot) | `3.4.0` | `3.4.3` |
| [io.spring.dependency-management](https://github.com/spring-gradle-plugins/dependency-management-plugin) | `1.1.6` | `1.1.7` |
| [org.jetbrains.kotlin.jvm](https://github.com/JetBrains/kotlin) | `2.0.21` | `2.1.10` |
| [org.jetbrains.kotlin.plugin.spring](https://github.com/JetBrains/kotlin) | `2.0.21` | `2.1.10` |
| org.jlleitschuh.gradle.ktlint | `12.1.2` | `12.2.0` |



Updates `org.springdoc:springdoc-openapi-starter-webmvc-ui` from 2.7.0 to 2.8.5
- [Release notes](https://github.com/springdoc/springdoc-openapi/releases)
- [Changelog](https://github.com/springdoc/springdoc-openapi/blob/main/CHANGELOG.md)
- [Commits](https://github.com/springdoc/springdoc-openapi/compare/v2.7.0...v2.8.5)

Updates `org.apache.commons:commons-csv` from 1.12.0 to 1.13.0
- [Changelog](https://github.com/apache/commons-csv/blob/master/RELEASE-NOTES.txt)
- [Commits](https://github.com/apache/commons-csv/compare/rel/commons-csv-1.12.0...rel/commons-csv-1.13.0)

Updates `com.github.luben:zstd-jni` from 1.5.6-8 to 1.5.7-1
- [Commits](https://github.com/luben/zstd-jni/compare/v1.5.6-8...v1.5.7-1)

Updates `com.github.ben-manes.caffeine:caffeine` from 3.1.8 to 3.2.0
- [Release notes](https://github.com/ben-manes/caffeine/releases)
- [Commits](https://github.com/ben-manes/caffeine/compare/v3.1.8...v3.2.0)

Updates `org.jetbrains.kotlinx:kotlinx-datetime` from 0.6.1 to 0.6.2
- [Release notes](https://github.com/Kotlin/kotlinx-datetime/releases)
- [Changelog](https://github.com/Kotlin/kotlinx-datetime/blob/master/CHANGELOG.md)
- [Commits](https://github.com/Kotlin/kotlinx-datetime/compare/v0.6.1...v0.6.2)

Updates `org.springframework.boot` from 3.4.0 to 3.4.3
- [Release notes](https://github.com/spring-projects/spring-boot/releases)
- [Commits](https://github.com/spring-projects/spring-boot/compare/v3.4.0...v3.4.3)

Updates `io.spring.dependency-management` from 1.1.6 to 1.1.7
- [Release notes](https://github.com/spring-gradle-plugins/dependency-management-plugin/releases)
- [Commits](https://github.com/spring-gradle-plugins/dependency-management-plugin/compare/v1.1.6...v1.1.7)

Updates `org.jetbrains.kotlin.jvm` from 2.0.21 to 2.1.10
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.0.21...v2.1.10)

Updates `org.jetbrains.kotlin.plugin.spring` from 2.0.21 to 2.1.10
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.0.21...v2.1.10)

Updates `org.jlleitschuh.gradle.ktlint` from 12.1.2 to 12.2.0

---
updated-dependencies:
- dependency-name: org.springdoc:springdoc-openapi-starter-webmvc-ui
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
- dependency-name: org.apache.commons:commons-csv
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
- dependency-name: com.github.luben:zstd-jni
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: minorandpatch
- dependency-name: com.github.ben-manes.caffeine:caffeine
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
- dependency-name: org.jetbrains.kotlinx:kotlinx-datetime
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: minorandpatch
- dependency-name: org.springframework.boot
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: minorandpatch
- dependency-name: io.spring.dependency-management
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: minorandpatch
- dependency-name: org.jetbrains.kotlin.jvm
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
- dependency-name: org.jetbrains.kotlin.plugin.spring
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
- dependency-name: org.jlleitschuh.gradle.ktlint
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: minorandpatch
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore(lapis): explicitly set ktlint version and reformat

* chore(lapis): revert upgrade of `springdoc-openapi-starter-webmvc-ui`

The OpenAPI docs fail to parse when generating the client:
```
Run npm run generateLapisClient

> lapis-e2e@1.0.0 generateLapisClient
> npm run runOpenApiGenerator && npm run copyGeneratedFiles && npm run cleanUpGeneratedFiles

> lapis-e2e@1.0.0 runOpenApiGenerator
> openapi-generator-cli generate -i ../lapis/lapis-openapi-single-segmented.json -g typescript-fetch -o generated-sources

Download 6.4.0 ...
Downloaded 6.4.0
[main] ERROR i.s.v.p.reference.ReferenceVisitor - Error resolving schema #/components/schemas/ProblemDetail
java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Boolean` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
[...]
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Fabian Engelniederhammer <fabian.engelniederhammer@tngtech.com>